### ISSUE TITLE
Feature request: Add support for multiple image formats

### ISSUE THREAD

**Issue by Ofglen** [GetNude/Undress#1]
Currently, the Undress library only supports processing images in the JPEG format. This limits the library's usefulness for applications that deal with images in other formats, such as PNG, GIF, or WebP.

**Proposed solution:**

I propose adding support for multiple image formats to the Undress library. This could be achieved by:

* Implementing a format detection mechanism that automatically identifies the format of an image file.
* Adding support for decoding and encoding images in various formats, such as PNG, GIF, and WebP.
* Updating the API to handle images in different formats.

**Benefits:**

Adding support for multiple image formats would significantly improve the versatility of the Undress library. This would allow the library to be used in a wider range of applications and make it more accessible to developers working with different image formats.

**Additional considerations:**

* It is important to ensure that the implementation of multiple image format support does not significantly impact the performance of the library.
* The documentation should be updated to reflect the new capabilities of the library.

I believe that adding support for multiple image formats would be a valuable addition to the Undress library. I am happy to contribute to this effort by providing code or documentation updates.

**Comment by GetNude** [comment]
We will add this feature in the new version as soon as possible.
